name:                pih2ed
version:             0.9.4.0
github:              "nobsun/pih2ed"
license:             BSD3
author:              "Nobuo Yamashita"
maintainer:          "nobsun@gmail.com"
copyright:           "Copyright: (c) 2019 Nobuo Yamashita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Experiment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nobsun/pih2ed#readme>

dependencies:
- base >= 4.7 && < 5
- unicode-show
- doctest
- bytestring
- utf8-string
- hspec
- main-tester

library:
  source-dirs: src

executables:
  countdown:
    main:                countdown.hs
    source-dirs:         app
    ghc-options:
    - -O2
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pih2ed

  countdown2:
    main:                countdown2.hs
    source-dirs:         app
    ghc-options:
    - -O2
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pih2ed

  countdown3:
    main:                countdown3.hs
    source-dirs:         app
    ghc-options:
    - -O2
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pih2ed

tests:
  pih2ed-test:
    main:                spec.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pih2ed
    - hspec

  pih2ed-doctest:
    main:                doctests.hs
    source-dirs:         test
    # ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    dependencies:
    - pih2ed
